<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li><li><span><a href="#Оглавление" data-toc-modified-id="Оглавление-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Оглавление</a></span></li><li><span><a href="#1.-Что-такое-NumPy" data-toc-modified-id="1.-Что-такое-NumPy-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1. Что такое NumPy</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Официальная-документация" data-toc-modified-id="Официальная-документация-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>Официальная документация</a></span></li></ul></li></ul></li><li><span><a href="#2.-NumPy-массивы" data-toc-modified-id="2.-NumPy-массивы-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2. NumPy массивы</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Массив-нулевой-размерности" data-toc-modified-id="Массив-нулевой-размерности-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>Массив нулевой размерности</a></span></li><li><span><a href="#Одномерный-массив" data-toc-modified-id="Одномерный-массив-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span>Одномерный массив</a></span></li><li><span><a href="#Двумерный-массив" data-toc-modified-id="Двумерный-массив-4.0.3"><span class="toc-item-num">4.0.3&nbsp;&nbsp;</span>Двумерный массив</a></span></li><li><span><a href="#Трехмерный-массив" data-toc-modified-id="Трехмерный-массив-4.0.4"><span class="toc-item-num">4.0.4&nbsp;&nbsp;</span>Трехмерный массив</a></span></li><li><span><a href="#Атрибут-ndim" data-toc-modified-id="Атрибут-ndim-4.0.5"><span class="toc-item-num">4.0.5&nbsp;&nbsp;</span>Атрибут <em>ndim</em></a></span></li><li><span><a href="#Массивы-большей-размерности" data-toc-modified-id="Массивы-большей-размерности-4.0.6"><span class="toc-item-num">4.0.6&nbsp;&nbsp;</span>Массивы большей размерности</a></span></li></ul></li></ul></li><li><span><a href="#3.-Индексация-элементов-массивов" data-toc-modified-id="3.-Индексация-элементов-массивов-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>3. Индексация элементов массивов</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#3.1.-Доступ-к-элементам-массива-по-индексу" data-toc-modified-id="3.1.-Доступ-к-элементам-массива-по-индексу-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>3.1. Доступ к элементам массива по индексу</a></span></li><li><span><a href="#3.2-Срезы" data-toc-modified-id="3.2-Срезы-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span>3.2 Срезы</a></span></li><li><span><a href="#3.3.-Шаг-step" data-toc-modified-id="3.3.-Шаг-step-5.0.3"><span class="toc-item-num">5.0.3&nbsp;&nbsp;</span>3.3. Шаг <em>step</em></a></span></li><li><span><a href="#3.4.-Срезы-в-двумерных-массивах" data-toc-modified-id="3.4.-Срезы-в-двумерных-массивах-5.0.4"><span class="toc-item-num">5.0.4&nbsp;&nbsp;</span>3.4. Срезы в двумерных массивах</a></span></li></ul></li></ul></li><li><span><a href="#4.-Типы-данных-в-массиве" data-toc-modified-id="4.-Типы-данных-в-массиве-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>4. Типы данных в массиве</a></span></li><li><span><a href="#5.-Копия-copy()-и-представление-view()" data-toc-modified-id="5.-Копия-copy()-и-представление-view()-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>5. Копия <em>copy()</em> и представление <em>view()</em></a></span></li><li><span><a href="#6.-Форма-массива-NumPy" data-toc-modified-id="6.-Форма-массива-NumPy-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>6. Форма массива NumPy</a></span></li><li><span><a href="#7.-Изменение-формы-массива-NumPy" data-toc-modified-id="7.-Изменение-формы-массива-NumPy-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>7. Изменение формы массива NumPy</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Какие-допускаются-преобразования-формы?" data-toc-modified-id="Какие-допускаются-преобразования-формы?-9.0.1"><span class="toc-item-num">9.0.1&nbsp;&nbsp;</span>Какие допускаются преобразования формы?</a></span></li><li><span><a href="#Копия-или-представление?" data-toc-modified-id="Копия-или-представление?-9.0.2"><span class="toc-item-num">9.0.2&nbsp;&nbsp;</span>Копия или представление?</a></span></li><li><span><a href="#Неизвестный-размер" data-toc-modified-id="Неизвестный-размер-9.0.3"><span class="toc-item-num">9.0.3&nbsp;&nbsp;</span>Неизвестный размер</a></span></li><li><span><a href="#Сглаживание-массива" data-toc-modified-id="Сглаживание-массива-9.0.4"><span class="toc-item-num">9.0.4&nbsp;&nbsp;</span>Сглаживание массива</a></span></li></ul></li></ul></li><li><span><a href="#8.-Итерация-массива-NumPy" data-toc-modified-id="8.-Итерация-массива-NumPy-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>8. Итерация массива NumPy</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Итерация-двумерного-массива" data-toc-modified-id="Итерация-двумерного-массива-10.0.1"><span class="toc-item-num">10.0.1&nbsp;&nbsp;</span>Итерация двумерного массива</a></span></li><li><span><a href="#Итерация-трехмерного-массива" data-toc-modified-id="Итерация-трехмерного-массива-10.0.2"><span class="toc-item-num">10.0.2&nbsp;&nbsp;</span>Итерация трехмерного массива</a></span></li><li><span><a href="#Итерация-массивов-с-помощью-nditer-()" data-toc-modified-id="Итерация-массивов-с-помощью-nditer-()-10.0.3"><span class="toc-item-num">10.0.3&nbsp;&nbsp;</span>Итерация массивов с помощью <em>nditer ()</em></a></span></li><li><span><a href="#Итерация-массива-с-другим-типом-данных" data-toc-modified-id="Итерация-массива-с-другим-типом-данных-10.0.4"><span class="toc-item-num">10.0.4&nbsp;&nbsp;</span>Итерация массива с другим типом данных</a></span></li><li><span><a href="#Пронумерованная-итерация-с-использованием-ndenumerate()" data-toc-modified-id="Пронумерованная-итерация-с-использованием-ndenumerate()-10.0.5"><span class="toc-item-num">10.0.5&nbsp;&nbsp;</span>Пронумерованная итерация с использованием <em>ndenumerate()</em></a></span></li></ul></li></ul></li><li><span><a href="#9.-Оси-массива" data-toc-modified-id="9.-Оси-массива-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>9. Оси массива</a></span></li><li><span><a href="#10.-Объединение-массивов" data-toc-modified-id="10.-Объединение-массивов-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>10. Объединение массивов</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Объединение-с-помощью-concatenate()" data-toc-modified-id="Объединение-с-помощью-concatenate()-12.0.1"><span class="toc-item-num">12.0.1&nbsp;&nbsp;</span>Объединение с помощью <em>concatenate()</em></a></span></li><li><span><a href="#Объединение-массивов-с-помощью-функции-укладки-stack()" data-toc-modified-id="Объединение-массивов-с-помощью-функции-укладки-stack()-12.0.2"><span class="toc-item-num">12.0.2&nbsp;&nbsp;</span>Объединение массивов с помощью функции укладки <em>stack()</em></a></span></li><li><span><a href="#Укладка-по-рядам" data-toc-modified-id="Укладка-по-рядам-12.0.3"><span class="toc-item-num">12.0.3&nbsp;&nbsp;</span>Укладка по рядам</a></span></li><li><span><a href="#Укладка-по-столбцам" data-toc-modified-id="Укладка-по-столбцам-12.0.4"><span class="toc-item-num">12.0.4&nbsp;&nbsp;</span>Укладка по столбцам</a></span></li><li><span><a href="#Укладка-по-высоте-(в-глубину)" data-toc-modified-id="Укладка-по-высоте-(в-глубину)-12.0.5"><span class="toc-item-num">12.0.5&nbsp;&nbsp;</span>Укладка по высоте (в глубину)</a></span></li></ul></li></ul></li><li><span><a href="#11.-Разделение-массивов" data-toc-modified-id="11.-Разделение-массивов-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>11. Разделение массивов</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Разделение-двумерных-массивов" data-toc-modified-id="Разделение-двумерных-массивов-13.0.1"><span class="toc-item-num">13.0.1&nbsp;&nbsp;</span>Разделение двумерных массивов</a></span></li></ul></li></ul></li><li><span><a href="#12.-Поиск-в-массивах" data-toc-modified-id="12.-Поиск-в-массивах-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>12. Поиск в массивах</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Поиск-с-помощью-where()" data-toc-modified-id="Поиск-с-помощью-where()-14.0.1"><span class="toc-item-num">14.0.1&nbsp;&nbsp;</span>Поиск с помощью <em>where()</em></a></span></li><li><span><a href="#Метод-searchsorted()" data-toc-modified-id="Метод-searchsorted()-14.0.2"><span class="toc-item-num">14.0.2&nbsp;&nbsp;</span>Метод <em>searchsorted()</em></a></span></li><li><span><a href="#Поиск-нескольких-значений" data-toc-modified-id="Поиск-нескольких-значений-14.0.3"><span class="toc-item-num">14.0.3&nbsp;&nbsp;</span>Поиск нескольких значений</a></span></li></ul></li></ul></li><li><span><a href="#13.-Сортировка-массивов" data-toc-modified-id="13.-Сортировка-массивов-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>13. Сортировка массивов</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Сортировка-двумерных-массивов" data-toc-modified-id="Сортировка-двумерных-массивов-15.0.1"><span class="toc-item-num">15.0.1&nbsp;&nbsp;</span>Сортировка двумерных массивов</a></span></li></ul></li></ul></li><li><span><a href="#14.-Фильтрация-массивов" data-toc-modified-id="14.-Фильтрация-массивов-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>14. Фильтрация массивов</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Фильтрация-массивов" data-toc-modified-id="Фильтрация-массивов-16.0.1"><span class="toc-item-num">16.0.1&nbsp;&nbsp;</span>Фильтрация массивов</a></span></li><li><span><a href="#Создание-массива-фильтров" data-toc-modified-id="Создание-массива-фильтров-16.0.2"><span class="toc-item-num">16.0.2&nbsp;&nbsp;</span>Создание массива фильтров</a></span></li><li><span><a href="#Создание-фильтра-непосредственно-из-массива" data-toc-modified-id="Создание-фильтра-непосредственно-из-массива-16.0.3"><span class="toc-item-num">16.0.3&nbsp;&nbsp;</span>Создание фильтра непосредственно из массива</a></span></li></ul></li></ul></li><li><span><a href="#15.-Случайные-числа-в-NumPy" data-toc-modified-id="15.-Случайные-числа-в-NumPy-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>15. Случайные числа в NumPy</a></span><ul class="toc-item"><li><span><a href="#14.1.-Введение" data-toc-modified-id="14.1.-Введение-17.1"><span class="toc-item-num">17.1&nbsp;&nbsp;</span>14.1. Введение</a></span><ul class="toc-item"><li><span><a href="#Псевдослучайное-и-истинное-случайное" data-toc-modified-id="Псевдослучайное-и-истинное-случайное-17.1.1"><span class="toc-item-num">17.1.1&nbsp;&nbsp;</span>Псевдослучайное и истинное случайное</a></span></li><li><span><a href="#Сгенерировать-случайное-число" data-toc-modified-id="Сгенерировать-случайное-число-17.1.2"><span class="toc-item-num">17.1.2&nbsp;&nbsp;</span>Сгенерировать случайное число</a></span></li><li><span><a href="#Случайный-массив" data-toc-modified-id="Случайный-массив-17.1.3"><span class="toc-item-num">17.1.3&nbsp;&nbsp;</span>Случайный массив</a></span></li><li><span><a href="#Случайное-число-массива" data-toc-modified-id="Случайное-число-массива-17.1.4"><span class="toc-item-num">17.1.4&nbsp;&nbsp;</span>Случайное число массива</a></span></li></ul></li><li><span><a href="#14.2.-Случайное-распределение-данных" data-toc-modified-id="14.2.-Случайное-распределение-данных-17.2"><span class="toc-item-num">17.2&nbsp;&nbsp;</span>14.2. Случайное распределение данных</a></span><ul class="toc-item"><li><span><a href="#Случайное-распределение" data-toc-modified-id="Случайное-распределение-17.2.1"><span class="toc-item-num">17.2.1&nbsp;&nbsp;</span>Случайное распределение</a></span></li></ul></li><li><span><a href="#14.3.-Случайные-перестановки" data-toc-modified-id="14.3.-Случайные-перестановки-17.3"><span class="toc-item-num">17.3&nbsp;&nbsp;</span>14.3. Случайные перестановки</a></span><ul class="toc-item"><li><span><a href="#Генерация-перестановок-массивов" data-toc-modified-id="Генерация-перестановок-массивов-17.3.1"><span class="toc-item-num">17.3.1&nbsp;&nbsp;</span>Генерация перестановок массивов</a></span></li></ul></li><li><span><a href="#14.4.-Нормальное-(гауссово)-распределение" data-toc-modified-id="14.4.-Нормальное-(гауссово)-распределение-17.4"><span class="toc-item-num">17.4&nbsp;&nbsp;</span>14.4. Нормальное (гауссово) распределение</a></span><ul class="toc-item"><li><span><a href="#Визуализация-нормального-распределения" data-toc-modified-id="Визуализация-нормального-распределения-17.4.1"><span class="toc-item-num">17.4.1&nbsp;&nbsp;</span>Визуализация нормального распределения</a></span></li></ul></li></ul></li><li><span><a href="#16.-Статистические-функции" data-toc-modified-id="16.-Статистические-функции-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>16. Статистические функции</a></span></li><li><span><a href="#17.-Универсальные-функции-ufunc" data-toc-modified-id="17.-Универсальные-функции-ufunc-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>17. Универсальные функции <em>ufunc</em></a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Функция-add(x,-y)" data-toc-modified-id="Функция-add(x,-y)-19.0.1"><span class="toc-item-num">19.0.1&nbsp;&nbsp;</span>Функция <em>add(x, y)</em></a></span></li><li><span><a href="#Функция-subtract()" data-toc-modified-id="Функция-subtract()-19.0.2"><span class="toc-item-num">19.0.2&nbsp;&nbsp;</span>Функция <em>subtract()</em></a></span></li><li><span><a href="#Функция-multiply()" data-toc-modified-id="Функция-multiply()-19.0.3"><span class="toc-item-num">19.0.3&nbsp;&nbsp;</span>Функция <em>multiply()</em></a></span></li><li><span><a href="#Функция-divide()" data-toc-modified-id="Функция-divide()-19.0.4"><span class="toc-item-num">19.0.4&nbsp;&nbsp;</span>Функция <em>divide()</em></a></span></li><li><span><a href="#Функция-power()" data-toc-modified-id="Функция-power()-19.0.5"><span class="toc-item-num">19.0.5&nbsp;&nbsp;</span>Функция <em>power()</em></a></span></li><li><span><a href="#Функции-mod()-и-reminder()" data-toc-modified-id="Функции-mod()-и-reminder()-19.0.6"><span class="toc-item-num">19.0.6&nbsp;&nbsp;</span>Функции <em>mod()</em> и <em>reminder()</em></a></span></li><li><span><a href="#Функции-округления" data-toc-modified-id="Функции-округления-19.0.7"><span class="toc-item-num">19.0.7&nbsp;&nbsp;</span>Функции округления</a></span></li><li><span><a href="#Логарифмирование" data-toc-modified-id="Логарифмирование-19.0.8"><span class="toc-item-num">19.0.8&nbsp;&nbsp;</span>Логарифмирование</a></span></li><li><span><a href="#Тригонометрические-функции-sin(),-cos(),-tan()" data-toc-modified-id="Тригонометрические-функции-sin(),-cos(),-tan()-19.0.9"><span class="toc-item-num">19.0.9&nbsp;&nbsp;</span>Тригонометрические функции <em>sin(), cos(), tan()</em></a></span></li><li><span><a href="#Тригонометрические-функции-arcsin(),-arccos(),-arctan()" data-toc-modified-id="Тригонометрические-функции-arcsin(),-arccos(),-arctan()-19.0.10"><span class="toc-item-num">19.0.10&nbsp;&nbsp;</span>Тригонометрические функции <em>arcsin(), arccos(), arctan()</em></a></span></li></ul></li></ul></li><li><span><a href="#18.-Распространение-broadcasting" data-toc-modified-id="18.-Распространение-broadcasting-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>18. Распространение <em>broadcasting</em></a></span></li><li><span><a href="#Задания" data-toc-modified-id="Задания-21"><span class="toc-item-num">21&nbsp;&nbsp;</span>Задания</a></span></li></ul></div>



<p style="font-size:150%">Лекция</p>

# Обработка и анализ данных в Numpy-массивах

<a id=Ref></a>
# Оглавление

[1. Что такое NumPy](#WhatIsNumPy)<br>
[2. Numpy массивы](#NumPyArrays)<br>
[3. Индексация](#Ind)<br>
[4. Типы данных](#dtype)<br>
[5. Копии и представления](#copy_and_view)<br>
[6. Форма массива](#shape)<br>
[7. Изменение формы массива](#shape_change)<br>
[8. Итерация](#iterating)<br>
[9. Оси Numpy-массива](#axes)<br>
[10. Объединение массивов](#con)<br>
[11. Разделение массивов](#split)<br>
[12. Поиск в массивах](#where)<br>
[13. Сортировка массивов](#sort)<br>
[14. Фильтрация массивов](#filter)<br>
[15. Случайные числа](#random)<br>
[16. Статистические функции](#func)<br>
[17. Универсальные функции](#ufunc)<br>
[18. Распространение](#broadc)<br>
[Задания](#task)

<a id=WhatIsNumPy></a>
[Оглавление](#Ref)|| [=>](#NumPyArrays)

# 1. Что такое NumPy

*NumPy* - это библиотека Python, используемая для работы с массивами. Она также имеет функции для операций линейной алгебры, преобразования Фурье и работы с матрицами. NumPy была создана в 2005 году Трэвисом Олифантом. Это проект с открытым исходным кодом и им можно свободно пользоваться. NumPy означает числовой Python.

В Python есть списки, но они относительно медленно обрабатываются. NumPy обеспечивает работу с массивами, которые обрабатываются до 50 раз быстрее, чем традиционные списки Python. Объект массива в NumPy называется *ndarray*. Массивы часто используются в науке о данных, где очень важны скорость и ресурсы.

Наука о данных - это отрасль информатики, в которой мы изучаем, как хранить, использовать и анализировать данные для получения информации.

Почему NumPy быстрее списков? В отличие от списков, массивы NumPy хранятся в одной непрерывной области памяти, поэтому процессы могут обращаться к ним и управлять ими очень эффективно. В информатике это называется локальностью ссылок. Также библиотека NumPy оптимизирована для работы с новыми архитектурами процессоров.

Библиотека NumPy частично написана на Python, но большинство частей, требующих быстрых вычислений, написаны на C или C ++.

Для установки NumPy достаточно выполнить команду

`C:\Users\Your Name>pip install numpy` 

NumPy входит в популярный пакет программ Anaconda, поэтому, если пакет Anaconda установлен, то библиотека NumPy также установлена.

Если NumPy установлена, то для работы с библиотекой ее необходимо импортировать с помощью команды

`import numpy`

Как правило, библиотеку NumPy импортируют с псевдонимом np.

`import numpy as np`

In [1]:
import numpy as np

Строка версии хранится в атрибуте `__version__`

```
print(np.__version__)

1.21.5
```

Узнать, какая последняя версия, можно на сайте https://numpy.org/

<img src="../Img/numpy_org.png" style="width:50%">

Для обновления библиотеки в Jupyter Notebook используется команда

`!pip install -U <имя библиотеки>`



In [3]:
print(np.__version__)

1.21.5


### Официальная документация
https://numpy.org/doc/stable/

<a id=NumPyArrays></a>

[ <= ](#WhatIsNumPy) || [Оглавление](#Ref)|| [=>](#Ind)

# 2. NumPy массивы

NumPy используется для работы с массивами. Массив NumPy является объектом *ndarray* (нд-массив). Мы можем создать объект *ndarray* с помощью функции *array()*.

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Чтобы создать *ndarray*, мы можем передать список или кортеж в метод *array()*, и он будет преобразован в *ndarray*:

In [5]:
arr = np.array((1, 2, 3, 4, 5))
print(arr) 

[1 2 3 4 5]


### Массив нулевой размерности

Массивами нулевой размерности (0-D), или скалярами, являются элементы массива. Каждое значение в массиве представляет собой массив нулевой размерности.

In [6]:
import numpy as np
arr = np.array(42)
print(arr)

42


### Одномерный массив
Одномерным является массив, элементами которого являются массивы нулевой размерности (скаляры).

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr) 

[1 2 3 4 5]


### Двумерный массив
Двумерным является массив, элементами которого являются одномерные массивы. Такие массивы часто используются для задания матриц. Создадим двумерный массив, содержащий два массива со значениями 1,2,3 и 4,5,6:

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### Трехмерный массив
Трехмерным массивом является массив, элементами которого являются двумерные массивы (матрицы)

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Атрибут *ndim*
Атрибут *ndim* возвращает число измерений массива

In [11]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim, b.ndim, c.ndim, d.ndim)

0 1 2 3


### Массивы большей размерности
Массив может иметь любое количество измерений. При создании массива количество измерений можно определить с помощью аргумента *ndmin*.

In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


В этом массиве самое внутреннее измерение (5-й размер) имеет 4 элемента, 4-й размер имеет 1 элемент, который является вектором, 3-й размер имеет 1 элемент, который является матрицей с вектором, 2-й размер имеет 1 элемент, который является трехмерным массивом и 1-й размер имеет 1 элемент, который является 4-мерным массивом.

<a id=Ind></a>
[ <= ](#NumPyArrays) || [Оглавление](#Ref)|| [=>](#dtype)

# 3. Индексация элементов массивов

### 3.1. Доступ к элементам массива по индексу

Доступ к элементам массива осуществляется по их индексу. Индексы в массивах NumPy начинаются с 0, что означает, что первый элемент имеет индекс 0, второй - индекс 1 и т. д.

In [13]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2] + arr[3]) 

1
2
7


Для доступа к элементу двумерного массива указывается два индекса через запятую.

In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Элемент [0,1]: ', arr[0, 1])
print('Элемент [1,4]: ', arr[1, 4]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Элемент [0,1]:  2
Элемент [1,4]:  10


Для доступа к элементам трехмерного массива указываются целые числа, разделенные запятыми, представляющие размеры и индекс элемента.

In [15]:
arr = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Использование отрицательных индексов

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1]) 

10


### 3.2 Срезы

[start:end] или [start:end:step]

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[:4])

[2 3 4 5]
[1 2 3 4]


Срезы с использованием отрицательных индексов

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1]) 

[5 6]


### 3.3. Шаг *step*

Пример 3.3.1

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) 

[2 4]


Пример 3.3.2

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


### 3.4. Срезы в двумерных массивах

Пример 3.4.1. Из 2-го элемента получить элементы с 1-го по 4-й (правая граница не включена)

In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) 

[7 8 9]


Пример 3.4.2. Из обоих элементов получить элементы с индексом 2.

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


Пример 3.4.3. Из обоих массивов получить элементы с индексами от 1 до 4, не включая правую границу. 

In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


<a id=dtype></a>
 [ <= ](#Ind) || [Оглавление](#Ref)|| [=>](#copy_and_view)
# 4. Типы данных в массиве
```
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
```

Объект массива NumPy имеет свойство с именем *dtype*, которое возвращает тип данных массива

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype) 

int32


In [25]:
arr = np.array(['яблоко', 'банан', 'вишня'])
print(arr.dtype)

<U6


Функция `array()` может принимать необязательный аргумент *dtype*, который позволяет определять ожидаемый тип данных элементов массива. Создадим массив с данными текстового типа.

In [26]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


Для i, u, f, S и U мы также можем определить размер. Создадим массив с типом данных "целое число 4 байта":

In [27]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


Что происходит, если преобразование типа невозможно? Если указан тип, в который элементы не могут быть преобразованы, NumPy вызовет ValueError. Пример. Строка, отличная от целого числа, например 'a', не может быть преобразована в целое число (вызовет ошибку)
```
arr = np.array(['a', '2', '3'], dtype='i')
---------------------------------------------------------------------------
ValueError  
```

Лучший способ изменить тип данных массива - сделать копию массива с помощью *astype()*.

Функция *astype()* создает копию массива и позволяет указать тип данных в качестве параметра.

Тип данных может быть указан с помощью строки, например `'f'` для вещественного числа, `'i'` для целого числа и т. д. Также тип данных может быть указан напрямую, например, *float* для вещественного числа и *int* для целого числа.

Изменим тип данных с *float* на *integer*, используя 'i' в качестве значения параметра:

In [28]:
arr = np.array([1.1, 2.1, 3.7])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


Изменим тип данных с целого на логический:

In [29]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


<a id=copy_and_view></a>
[ <= ](#dtype) || [Оглавление](#Ref)|| [=>](#shape)
# 5. Копия *copy()* и представление *view()*
Основное различие между копией и представлением массива в том, что копия - это новый массив, а представление - это просто представление исходного массива.

Копия хранит свои данные, и изменения, внесенные в копию, не повлияют на исходный массив, а изменения, внесенные в исходный массив, не повлияют на копию.

Представление не владеет данными, и любые изменения, внесенные в представление, повлияют на исходный массив, а любые изменения, внесенные в исходный массив, повлияют на представление.

Сделаем копию, изменим исходный массив и отобразим оба массива:

In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 9

print(arr)
print(x)

[9 2 3 4 5]
[1 2 3 4 5]


Создадим представление, изменим <u>исходный массив</u> и отобразим оба массива:

In [31]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Создадим представление, изменим <u>представление</u> и отобразим оба массива:

In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Копии хранят данные, а представления не хранят данных, но как это проверить?

Каждый массив NumPy имеет атрибут *base*, который возвращает None, если массив хранит свои данные. В противном случае атрибут *base* ссылается на исходный объект.

In [33]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


<a id=shape></a>
[ <= ](#copy_and_view) || [Оглавление](#Ref)|| [=>](#shape_change)
# 6. Форма массива NumPy

Форма массива - это количество элементов в каждом измерении. Массивы NumPy имеют атрибут *shape*, который возвращает кортеж, каждое значение которого указывает на длину массива по соотвектствующей оси. В следующем примере массив имеет два измерения и в каждом четыре элемента.

In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) 

(2, 4)


Пример 6.1. Создать массив с пятью измерениями, используя *ndmin* и вектор со значениями 1,2,3,4, и убедиться, что последнее измерение имеет значение 4:

In [35]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Форма массива :', arr.shape)

[[[[[1 2 3 4]]]]]
Форма массива : (1, 1, 1, 1, 4)


Что представляет собой кортеж формы массива? Числа кортежа указывают на число элементов по каждому измерению. В этом примере последний элемент кортежа (с индексом 4) имеет значение 4, поэтому 5-е измерение массива содержит 4 элемента.

Чтобы получить доступ к элементу массива, следует указать его индексы по соответствующей оси.

Пример 6.2. Получить число с индексом 2 в последнем измерении.

In [47]:
print(arr[0][0][0][0][2])
print(arr[0,0,0,0,2])

3
3


<a id=shape_change></a>
[ <= ](#shape) || [Оглавление](#Ref)|| [=>](#iterating)
# 7. Изменение формы массива NumPy

Изменяя форму, мы можем добавлять или удалять размеры или изменять количество элементов в каждом измерении.

Пример 7.1.<br>
Преобразуйте следующий одномерный массив с 12 элементами в двухмерный массив.<br> В результате по самому внешнему измерению получим 4 массива по 3 элемента в каждом:

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Пример 7.2.<br>
Преобразуйте следующий одномерный массив с 12 элементами в трехмерный массив.<br>
Самое внешнее измерение будет иметь 2 массива, содержащих 3 массива, каждый с 2 элементами:

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Какие допускаются преобразования формы?
Любые при условии, что число элементов в обоих формах одинаково.
```
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
-----------------------------------------------------------
----> 3 newarr = arr.reshape(3, 3)
ValueError: cannot reshape array of size 8 into shape (3,3)
```

### Копия или представление?

In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


В приведенном выше примере возвращается исходный массив, поэтому это представление.

### Неизвестный размер
NumPy разрешает иметь одно «неизвестное» измерение. Это означает, что точное число для одного из размеров можно не указывать. Передайте -1 в качестве значения, и NumPy вычислит это число за вас.

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<i>Примечание</i>. Значение -1 можно указывать только один раз при задании формы.

### Сглаживание массива

Сглаживание массива означает преобразование многомерного массива в одномерный массив. Для этого мы можем использовать `reshape(-1)`.

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


<i>Примечание</i>. Существует множество функций для изменения форм массивов в numpy: *flatten, ravel*, а также для переупорядочивания элементов: *rot90, flip, fliplr, flipud* и т. д.

<a id=iterating></a>
[ <= ](#shape_change) || [Оглавление](#Ref)|| [=>](#axes)
# 8. Итерация массива NumPy
Итерация означает прохождение элементов один за другим. Итерация в Пайтон осуществляется с помощью цикла *for*.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

### Итерация двумерного массива

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


### Итерация трехмерного массива

In [76]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)
print()

for x in arr:
    for y in x:
        print(y, end=' ')
print()
print()

for x in arr:
    for y in x:
        for z in y:
            print(z, end=' ')

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[1 2 3] [4 5 6] [7 8 9] [10 11 12] 

1 2 3 4 5 6 7 8 9 10 11 12 

### Итерация массивов с помощью *nditer ()*
Функция *nditer()* - это вспомогательная функция, которую можно использовать от самых простых до очень сложных итераций. Она решает некоторые основные проблемы, с которыми мы сталкиваемся в итерации.

Пример. Итерация 3-х мерного массива.

In [77]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x) 

1
2
3
4
5
6
7
8


### Итерация массива с другим типом данных

Мы можем использовать аргумент *op_dtypes* и передать ему ожидаемый тип данных, чтобы изменить тип данных элементов во время итерации.

NumPy не изменяет тип данных элемента на месте (где элемент находится в массиве), поэтому для выполнения этого действия требуется какое-то другое пространство, это дополнительное пространство называется буфером, и чтобы включить его в *nditer()*, мы передаем `flags=['buffered']`.

In [78]:
arr = np.array([1, 2, 3])
a=[]
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    a.append(x)
    print(x)

b'1'
b'2'
b'3'


<p style="color:gray"><i>Примечание.</i> Префикс <i>b</i> перед строкой означает строку в бинарном формате. Такие строки могут содержать символы только в кодировке ASCII.</p>

Итерация с разным размером шага. Мы можем использовать фильтрацию с последующей итерацией.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

### Пронумерованная итерация с использованием *ndenumerate()*

В ходе пронумерованной итерации возвращается порядковый номер шага итерации. Используется, если необходимо получить индекс элемента во время итерации.

Пример 1.

In [79]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


Пример 2.

In [80]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


<a id=axes></a>
[ <= ](#iterating) || [Оглавление](#Ref)|| [=>](#con)

# 9. Оси массива

Оси Numpy-массива $-$ это направления вдоль строк и столбцов.

<img src="../Img/numpy-arrays-have-axes.png" style="width:50%">

<a id=con></a>
[ <= ](#axes) || [Оглавление](#Ref)|| [=>](#split)

# 10. Объединение массивов

### Объединение с помощью *concatenate()*

Объединение означает размещение содержимого двух или более массивов в одном массиве.

В SQL мы объединяем таблицы на основе ключа, тогда как в NumPy мы объединяем массивы по осям. Мы передаем последовательность массивов, которые хотим присоединить, к функции *concatenate()* вместе с осью. Если ось явно не задана, она принимается равной 0.

In [85]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


Объединение двумерных массивов вдоль строк

In [87]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

[[1 2 5 6]
 [3 4 7 8]]


### Объединение массивов с помощью функции укладки *stack()*

Объединение с помощью функции укладки такое же, как и конкатенация, с той лишь разницей, что наложение выполняется по новой оси. Мы можем объединить два одномерных массива вдоль второй оси, что приведет к их размещению друг над другом, т.е. штабелирование. Если ось явно не передана, она принимается равной 0.

In [88]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Укладка по рядам

NumPy предоставляет вспомогательную функцию: `hstack()` для укладки вдоль строк.

In [89]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


### Укладка по столбцам

NumPy предоставляет вспомогательную функцию: *vstack()* для укладки по столбцам.

In [90]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Укладка по высоте (в глубину)
NumPy предоставляет вспомогательную функцию: *dstack()* для стека по высоте.

In [91]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


<a id=split></a>
[ <= ](#con) || [Оглавление](#Ref)|| [=>](#where)


# 11. Разделение массивов

Разделение - это операция, обратная объединению.

Объединение объединяет несколько массивов в один, а разделение разбивает один массив на несколько.

Мы используем *array_split()* для разделения массивов, мы передаем ему массив, который мы хотим разделить, и количество разделений.

In [92]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


Примечание. Результатом является массив, содержащий три массива.

Разделим массив на четыре части.

In [93]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Примечание: также есть метод *split()*, но он не будет разделять, когда в исходном массиве меньше элементов для разделения, как в примере выше. *array_split()* работет корректно, но *split()* в таком случае возвращает ошибку.

Доступ к результатам *array_split()* осуществляется по индексу массива.

In [94]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


### Разделение двумерных массивов

Используйте тот же синтаксис при разделении двумерных массивов. Используйте метод *array_split()*, передайте массив, и количество разделений. В результате выполнения следующей ячейки массив разделяется на три двумерных массива. 

In [95]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


В следующем примере каждый элемент двумерного массива содержит три элемента.

In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


Кроме того, можно указать, по какой оси делать разделение.

В приведенном ниже примере также возвращаются три двумерных массива, но они разделены по строке (ось = 1).

In [97]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Как альтернативу можно применить *hsplit()* - противоположенность *hstack()*. Также существуют методы *vsplit()* и *dsplit()*, выполняющие обратные действия по сравнению с *vstack()* и *dstack()*.

In [98]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


<a id=where></a>
[ <= ](#split) || [Оглавление](#Ref)|| [=>](#sort)

# 12. Поиск в массивах

### Поиск с помощью *where()*
Вы можете искать в массиве определенное значение и возвращать найденные индексы. Для поиска в массиве используется метод *where()*.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

Пример. Найти индексы элементов, принимающих четные значения.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

Пример. Найдите индексы элементов с нечетными значениями.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

### Метод *searchsorted()*

Метод *searchsorted()* выполняет двоичный поиск в массиве и возвращает индекс, в который будет вставлено указанное значение для поддержания порядка поиска. Предполагается, что метод *searchsorted()* используется для отсортированных массивов.

Пример. Найти индекс элемента, на место которого следует вставить число семь.

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

Метод начинает поиск слева и возвращает первый индекс, в котором число 7 не больше следующего значения.

По умолчанию возвращается крайний левый индекс, но вместо этого мы можем указать `side = 'right'`, чтобы вернуть крайний правый индекс.

Пример. Найдите индексы, в которые нужно вставить значение 7, начиная справа.

In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

Объяснение примера: число 7 следует вставить с индексом 2, чтобы сохранить порядок сортировки. Метод начинает поиск справа и возвращает первый индекс, начиная с которого число 7 не меньше следующего значения.

### Поиск нескольких значений

Чтобы найти более одного значения, используйте массив с указанными значениями.

Пример. Найти индексы, в которые нужно вставить значения 2, 4 и 6.

In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

<a id=sort></a>
[ <= ](#where) || [Оглавление](#Ref)|| [=>](#filter)

# 13. Сортировка массивов

Сортировка означает размещение элементов в упорядоченной последовательности.

Упорядоченная последовательность - это любая последовательность, которая имеет порядок, соответствующий элементам, например числовой или алфавитный, по возрастанию или по убыванию.

В объекте NumPy ndarray есть функция *sort()*, которая сортирует указанный массив.

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) 

Примечание. Этот метод возвращает копию массива, оставляя исходный массив без изменений.

Пример. Сортировка по алфавиту.

In [ ]:
arr = np.array(['банан', 'вишня', 'яблоко'])

print(np.sort(arr)) 

Пример. Сортировка логических значений.

In [ ]:
arr = np.array([True, False, True])

print(np.sort(arr))

### Сортировка двумерных массивов
При сортирвке двумерного массива методом *sort()*, оба массива сортируются.

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

<a id=filter></a>

[ <= ](#sort) || [Оглавление](#Ref)|| [=>](#random)

# 14. Фильтрация массивов

### Фильтрация массивов

Получение некоторых элементов из существующего массива и создание из них нового массива называется фильтрацией.

В NumPy для фильтрации используется список логических индексов. Список логических индексов - это список логических значений, соответствующих индексам в массиве.

Если значение логического индекса *True*, элемент содержится в фильтруемом массиве, если значение *False*, этот элемент исключается из фильтруемого массива.

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr) 

### Создание массива фильтров

В приведенном выше примере мы жестко запрограммировали значения True и False, но обычно они используются для создания массива фильтров на основе условий.

Пример. Создать массив фильтров, который будет возвращать только значения больше 42.

In [ ]:
arr = np.array([41, 42, 43, 44])

# Создать пустой список
filter_arr = []

# цикл по всем элемента массива
for element in arr:
  # если элемент больше 42, добавить значение True, иначе False
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

# применить фильтр, результат сохранить в новом массиве
newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

Задание. Создать массив фильтров, который будет возвращать только четные элементы из исходного массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []

# Ваш код здесь


### Создание фильтра непосредственно из массива

Приведенный выше пример - довольно распространенная задача в NumPy, и NumPy предоставляет хороший способ ее решить.

Мы можем напрямую подставить массив вместо итерируемой переменной в нашем условии, и оно будет работать так, как мы ожидаем.

Пример. Создать массив фильтров, который будет возвращать только значения больше 42.

In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

Задание. Создать массив фильтров, который будет возвращать только четные элементы из исходного массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Ваш код здесь

<a id=random></a>

[ <= ](#filter) || [Оглавление](#Ref)|| [=>](#func)

# 15. Случайные числа в NumPy

Случайность означает то, что нельзя предсказать логически.

## 14.1. Введение

### Псевдослучайное и истинное случайное

Компьютеры работают по программам, а программы представляют собой окончательный набор инструкций. Значит, должен быть какой-то алгоритм для генерации случайного числа.

Если есть программа для генерации случайного числа, его можно предсказать, поэтому оно не является действительно случайным.

Случайные числа, сгенерированные с помощью алгоритма генерации, называются псевдослучайными.

Можем ли мы получить действительно случайные числа?

Да. Чтобы сгенерировать действительно случайное число на наших компьютерах, нам нужно получить случайные данные из какого-то внешнего источника. Этим внешним источником обычно являются наши нажатия клавиш, движения мыши, данные в сети и т. д.

Нам не нужны действительно случайные числа, если только это не связано с безопасностью (например, ключи шифрования) или основанием для применения является случайность (например, колеса цифровой рулетки).

В этой лекции мы будем использовать псевдослучайные числа.

### Сгенерировать случайное число

NumPy предлагает модуль *random* для работы со случайными числами. Метод *randint()* позволяет сгенерировать случайное целое число.

Пример. Сгенерировать случайное целое число от 0 до 100:

In [ ]:
from numpy import random

x = random.randint(100)

print(x)

Метод *rand()* модуля *random* возвращает случайное вещественное число от 0 до 1.

In [ ]:
x = random.rand()
print(x) 

### Случайный массив

Пример. Сгенерировать одномерный массив, содержащий 5 случайных целых чисел от 0 до 100.

In [ ]:
from numpy import random

x = random.randint(100, size=(5))
print(x) 

Пример. Сгенерировать двумерный массив с 3 строками, каждая строка содержит 5 случайных целых чисел от 0 до 100.

In [ ]:
x = random.randint(100, size=(3, 5))
print(x)

Метод *rand()* также позволяет указать форму массива.

In [ ]:
x = random.rand(5)
print(x)

In [ ]:
x = random.rand(3, 5)
print(x)

### Случайное число массива
Метод *choice()* позволяет генерировать случайное значение на основе массива значений. Метод *choice()* принимает в качестве параметра массив и случайным образом возвращает одно из значений.

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

Метод *choice()* также позволяет возвращать массив значений. Добавьте параметр размера, чтобы указать форму массива.

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x) 

## 14.2. Случайное распределение данных

Распределение данных - это список всех возможных значений и того, как часто встречается каждое значение. Такие списки важны при работе со статистикой и наукой о данных.

Модуль *random* предлагает методы, которые возвращают случайно сгенерированные распределения данных.

### Случайное распределение

Случайное распределение - это набор случайных чисел, которые следуют определенной функции плотности вероятности.

Функция плотности вероятности: функция, описывающая непрерывную вероятность. т.е. вероятность всех значений в массиве.

Мы можем генерировать случайные числа на основе определенных вероятностей, используя метод *choice()* случайного модуля. Метод *choice()* позволяет нам указать вероятность для каждого значения. Вероятность задается числом от нуля до одного.

Пример<br>
Создайте одномерный массив, содержащий 100 значений, где каждое значение должно быть 3, 5, 7 или 9.<br>
Вероятность того, что значение будет равно 3, установлена ​​равной 0,1.<br>
Вероятность того, что значение будет 5, установлена ​​равной 0,3.<br>
Вероятность того, что значение будет равно 7, составляет 0,6.<br>
Вероятность того, что значение будет равно 9, установлена ​​равной 0.<br>

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

Примечание. Сумма вероятностей *p* должна быть равна единице.

Пример. Тот же пример, что и выше, но создается двумерный массив с 3 строками, каждая из которых содержит 5 значений.

In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,5))

print(x)

## 14.3. Случайные перестановки

Перестановка относится к расположению элементов. например, [3, 2, 1] - это перестановка [1, 2, 3] и наоборот. Модуль NumPy Random предоставляет для этого два метода: *shuffle()* и *permutation()*.

Пример.<br>
Случайным образом перемешать элементы массива.

In [ ]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

### Генерация перестановок массивов
Пример. Сгенерируйте случайную перестановку элементов следующего массива.

In [ ]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

## 14.4. Нормальное (гауссово) распределение

Нормальное распределение - одно из самых важных распределений. Его также называют распределением Гаусса в честь немецкого математика Карла Фридриха Гаусса. Оно соответствует распределению вероятностей многих событий, например показатели IQ, сердцебиение и т. д.

Используйте метод *random.normal()*, чтобы получить нормальное распределение данных. У него три параметра:

- loc - (среднее) там, где пик колокола.
- scale - (стандартное отклонение) - насколько ровным должно быть распределение графа.
- size - форма возвращаемого массива.

Пример. Сгенерируйте случайное нормальное распределение в массиве размером 2x3:

In [ ]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

Пример. Сгенерировать случайное нормальное распределение размера 2x3 со средним значением 1 и стандартным отклонением 2.

In [ ]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x) 

### Визуализация нормального распределения

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(size=1000, loc=11), hist=False)

plt.show()

<a id=func></a>

[ <= ](#random) || [Оглавление](#Ref)|| [=>](#ufunc)

# 16. Статистические функции

Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Рассмотрим, как они работают, на примере данных об урожае, собранном на частных приусадебных участках. Пусть имеется шесть участков, которым присвоим идентификаторы от 1 до 6. На каждом участке собрано яблок 135, 160, 163, 147, 138, 149 кг.; груш 68, 86, 80, 44, 82, 108 кг.; клубники 8, 11, 8.6, 10, 9.4, 7.8 кг. Поместим эти данные в массив.

In [ ]:
id=[1,2,3,4,5,6]
apples=[135, 160, 163, 147, 138, 149]
pears=[68, 86, 80, 44, 82, 108]
strawberries = [8, 11, 8.6, 10, 9.4, 7.8]
harvest=np.stack((id, apples, pears, strawberries),axis=1)
print(harvest)

Рассчитаем статистические характеристики данных об урожае. Средний урожай клубники:

In [ ]:
np.mean(harvest[:,-1])

Медианное значение урожая клубники

In [ ]:
np.median(harvest[:,-1])

Корреляция - статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Найдем значение корреляции данных об урожайности груш и яблок.

In [ ]:
np.corrcoef(harvest[:,1], harvest[:,2])

Рассчитаем стандартное отклонение урожая яблок, груш и клубники.

In [ ]:
for i in range(1,harvest.shape[1]):
    print(np.std(harvest[:,i]))

Рассчитаем максимальное и минимальное значения урожая по каждой позиции.

In [ ]:
for i in range(1,harvest.shape[1]):
    print(f'мин.: {np.min(harvest[:,i])} \t макс.: {np.max(harvest[:,i])}')

<a id=ufunc></a>
[ <= ](#func) || [Оглавление](#Ref)|| [=>](#broadc)

# 17. Универсальные функции *ufunc*

Универсальные функции используются для реализации векторизации в NumPy. Векторизацией называется преобразование итерационных операторов в векторную операцию.

### Функция *add(x, y)*

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3, 4]
list2 = [4, 5, 6, 7]
z = np.add(list1, list2)
print(z)

Функция *add()* выполняет операции не только со списками, но и с массивами.

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)

### Функция *subtract()*
Функция *subtract()* вычитает значения одного массива из  значений из другого массива и возвращает результаты в новом массиве.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

### Функция *multiply()*
Функция *multiply()* умножает значения одного массива на значения другого массива и возвращает результаты в новом массиве.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

### Функция *divide()*
Функция *div()* делит значения одного массива на значения другого массива и возвращает результаты в новом массиве.

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr) 

### Функция *power()*
Функция *power()* возводит значения первого массива в степень значений второго массива и возвращает результаты в новом массиве.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 4, 5, 6, 5, 4])

newarr = np.power(arr1, arr2)

print(newarr)

### Функции *mod()* и *reminder()*

Обе функции *mod()* и *remainder()* находят остаток от деления значений в первом массиве на соответствующие значения во втором массиве и возвращают результаты в новом массиве.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

### Функции округления
Для округления элементов массива используются функции
- trunc() и fix()
- around()
- floor()
- ceil()

### Логарифмирование
NumPy обеспечивает логарифмирование по основаниям $2, e, 10$.

In [ ]:
arr = np.arange(1, 10)
print(np.log2(arr)) 

Функция `arange(1, 10)` возвращает массив с целыми числами от 1 (включено) до 10 (не включено).

In [ ]:
arr = np.arange(1, 10)
print(np.log10(arr)) 

Натуральный логарифм или логарифм по основанию $e$

In [ ]:
arr = np.arange(1, 10)

print(np.log(arr))

NumPy не предоставляет функции для логарифмированию по любому основанию, поэтому мы можем использовать функцию *frompyfunc()* вместе со встроенной функцией *math.log()* с двумя входными параметрами и одним выходным параметром

In [ ]:
from math import log
nplog = np.frompyfunc(log, 2, 1)

print(nplog(225, 15)) 

Или воспользоваться свойствами логарифмов. Найдем логарифм 225 по основанию 15.

In [ ]:
arr1=np.array([225])
arr2=np.array([15])
print(np.log(arr1)/np.log(arr2))

### Тригонометрические функции *sin(), cos(), tan()*

Найти значение $ sin(\frac{\pi}{2}) $

In [ ]:
x = np.sin(np.pi/2)
print(x)

Найти значение для всех элементов массива

In [ ]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x) 

Построим график функции
$$
f(x)=x\cdot{sin(x)}
$$

In [ ]:
import matplotlib.pyplot as plt

x=np.linspace(-20,20,100)
f=np.multiply(x,np.sin(x))

plt.plot(x,f)
plt.plot(0, 0, color='red', marker="p")

### Тригонометрические функции *arcsin(), arccos(), arctan()*

NumPy предоставляет универсальные функции *arcsin(), arccos() arctan()*, которые производят значения в радианах для соответствующих заданных значений *sin, cos, tan*.

Пример. Найти угол, синус которого равен 1.

In [ ]:
x = np.arcsin(1.0)

print(x)

Дан массив синусов. Найти углы.

In [ ]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

<a id=broadc></a>
[ <= ](#ufunc) || [Оглавление](#Ref)|| [=>](#task)

# 18. Распространение *broadcasting*

В качестве аргументов универсальных функций могут выступать массивы различной, но сравнимой формы. В этом случае применяется механизм __распространения (broadcsting)__.

<img src="../Img/broadcasting1.png" alt="Обход элементов массива"/>

В примере скаляр распространяется до массива размерности (5,)

In [2]:
a = np.arange(5)
b = 10
c = a + b
print(c)

[10 11 12 13 14]


<img src="../Img/broadcasting2.png" alt="Пример распространения" style="width: 600px;"/>
Пример распространения для двух массивов размерности (3,2) и (3,1)

In [ ]:
a = np.arange(6).reshape(3, 2)
print(a2)

b = np.array([10,20,30]).reshape(3, 1)
print(b)

c = a + b
print(c)

Правила выполнения распространения: 
* соответствующие измерения двух массивов должны либо совпадать,
* либо одно из них должно быть равно единице. 

Если в одном из массивов не хватает измерений, то считается, что недостающее количество измерений - это младшие измерения (измерения с наименьшими номерами), которым приписывается размерность 1.
<br><br>

<img src="../Img/broadcasting3.png" alt="Пример работы с размерностями массивов" style="width: 500px;"/>

Примеры

In [ ]:
A = np.array([1,2,3])
B = np.array(([1,2,3], [4,5,6]))
print(A.shape, B.shape)
C = A + B
print(C)

In [ ]:
A = np.arange(6).reshape(6,1)
B = np.ones(24).reshape(1,6,4)
print(A.shape, B.shape)
C = A + B
print(C)
print(C.shape)

<a id=task></a>
[ <= ](#ufunc) || [Оглавление](#Ref)|| [=>](#task)

# Задания

1. Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [ ]:
import numpy as np

#1

a,b=[1,1,1],[3,3,3]

# Ваш код здесь


2. Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [ ]:
#2. Ваш код здесь


3. Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [ ]:
# 3. Ваш код здесь


4. Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент массива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [ ]:
# 4. Ваш код здесь


5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [ ]:
# 5. 

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

# Ваш код здесь


6. Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [ ]:
# 6. Ваш код здесь


7. Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [ ]:
# 7. Ваш код здесь


8. Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [ ]:
# 8. Ваш код здесь


9. Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [ ]:
#9

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

# Ваш код здесь


10. Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [ ]:
# 10. Ваш код здесь


11. Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [ ]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь
